mode = "yield"

[yield]
num_samples = 128

[parameters]
Btotal  = {nominal = 1, variance = 0.1}
Ltotal  = {nominal = 1, variance = 0.1}
Itotal  = {nominal = 1, variance = 0.1}

[verify]
method = "spec_file"
circuit = "data/test_splitt_changed_sym.js"
file = "data/test_splitt_changed_sym.sp"
