mode = "margin"

[margin]
max_search = 1.9
min_search = 0.1
scan_steps = 4
binary_search_steps = 3

[parameters]
Btotal = {"nominal" = 1}
Ltotal = {"nominal" = 1}
Itotal = {"nominal" = 1}

[verify]
method = "spec_file"
circuit = "data/test_splitt_changed_sym.js"
file = "data/test_splitt_changed_sym.sp"
