mode = "margin"

[margin]
max_search = 1.9
min_search = 0.1
scan_steps = 3
binary_search_steps = 10

[parameters]
Btotal = {"nominal" = 1}
Ltotal = {"nominal" = 1}
Itotal = {"nominal" = 1}

[verify]
method = "spec_file"
circuit = "data/example_splitter.cir"
file = "data/example_splitter.sp"
