mode = "margin"

[parameters]

#Globals
Btotal = {"nominal" = 1}
Ltotal = {"nominal" = 1}
Itotal = {"nominal" = 1}

# Junctions
B01rx2_unscaled = {"nominal" = 1}
B01tx1_unscaled = {"nominal" = 2}
B1_unscaled = {"nominal" = 3.25}
B2_unscaled = {"nominal" = 2.5}

# Currents
IB01rx2_unscaled = {"nominal" = 155e-6}
IB01tx1_unscaled = {"nominal" = 130e-6}
IB1_unscaled = {"nominal" = 569e-6}

# Inductors
L01_rx2_unscaled = {"nominal" = 0.2e-12}
L01_tx1_unscaled = {"nominal" = 2.5e-12}
L02_tx1_unscaled = {"nominal" = 3.3e-12}
L03_tx1_unscaled = {"nominal" = 8e-12}
L1_unscaled = {"nominal" = 1.4e-12}
L2_unscaled = {"nominal" = 2e-12}
L3_unscaled = {"nominal" = 0.4e-12}
L4_unscaled = {"nominal" = 1.9e-12}
L5_unscaled = {"nominal" = 2e-12}

[verify]
method = "spec_file"
circuit = "data/example_splitter.cir"
file = "data/example_splitter.sp"
