site_name: JoSIM Tools Documentation
repo_url: https://github.com/JoeyDelp/josim-tools
repo_name: JoeyDelp/josim-tools
site_author: Johannes Delport
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Configuration: 'configuration_file.md'
    - Example Usage: 'example_usage.md'

theme: 
  name: material
  palette:
    scheme: preference
    primary: black
  highlightjs: true
  hljs_languages:
    - bash
    - c++
    - python
  favicon: img/favicon.ico
  logo: img/favicon.ico
  features:
    - toc.integrate
    - header.autohide
  icon:
    repo: fontawesome/brands/github-alt
site_dir: build/mkdocs

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://unpkg.com/mermaid/dist/mermaid.min.js
    
plugins:
    - mermaid2

markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: True
      repo_url_shortener: True
      hide_protocol: True
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid  
  - pymdownx.highlight:
      linenums: false
  - mdx_math

    
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/JoeyDelp
          name: JoeyDelp on GitHub
          
copyright: Copyright &copy; 2021 Johannes Delport