mode = "margin"

[parameters]
Btotal = {"nominal" = 0.97147707}
Ltotal = {"nominal" = 0.94654473}
Itotal = {"nominal" = 1.03305609}

[verify]
method = "spec_file"
circuit = "data/example_splitter.cir"
file = "data/example_splitter.sp"
