mode="margin"

[parameters]
Itotal = {nominal = 1}
Jtotal = {nominal = 1}
Ltotal = {nominal = 1}
Rtotal = {nominal = 1}
LD_margin = {nominal = 0.44350714}
LQ_margin = {nominal = 1.56640472}
LO_margin = {nominal = 0.89742061}
LREL_margin = {nominal = 0.55096671}
J1_margin = {nominal = 1.01042576}
J2_margin = {nominal = 0.91381355}
J3_margin = {nominal = 0.93499926}
J4_margin = {nominal = 0.91727843}
I1_margin = {nominal = 1.21811015}

[margin]
binary_search_steps=12
scan_steps=2

[verify]
method="spec_file"
circuit="dff_starting_values.cir"
file="dff_specification.sp"
threshold=0.2
